######################################################################
# Automatically generated by qmake (3.0) Wed Apr 9 00:49:39 2014
######################################################################

TEMPLATE = app
TARGET = pragma
INCLUDEPATH += . ../lib/zlib-1.2.8/include ../lib/base64
LIBPATH += ../lib/zlib-1.2.8/lib ../lib/base64
LIBS += -lz -lbase64

# Input
SOURCES += main.cpp
